name: Android Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    permissions:
      checks: write

      pull-requests: write

      contents: read

      issues: read

      actions: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: set up Android SDK

      - name: Run ktlint
        run: ./gradlew ktlintCheck
