name: Gradle Clean CI

on:
  pull_request:
    branches:
      - main

jobs:
  gradle-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run gradle clean
        run: ./gradlew clean