name: Gradle Clean & ktlint

on: [push, pull_request]

jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Gradle clean
        run: ./gradlew clean

      - name: Run ktlint check
        run: ./gradlew ktlintCheck